baseurl: ""
url: http://technicalrex.com

title: Technical Rex
description: RAWR

google_analytics: UA-62666024-3

markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

sass:
  sass_dir: _sass
  style: :compressed
